defmodule CiBookTracker.Repo.Migrations.CreateReadingLogsAndBooks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:reading_logs, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :word_goal, :bigint, null: false
      add :language_code, :text, null: false
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:books, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :notes, :text
      add :finished_on, :date
      add :started_on, :date
      add :added_on, :date, null: false
      add :status, :text, null: false
      add :difficulty_label, :text
      add :estimated_words, :bigint
      add :page_count, :bigint
      add :author, :text
      add :title, :text, null: false

      add :reading_log_id,
          references(:reading_logs,
            column: :id,
            name: "books_reading_log_id_fkey",
            type: :uuid,
            on_delete: :delete_all
          ), null: false

      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `books` table without the `books_reading_log_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:books)

    drop table(:reading_logs)
  end
end