defmodule CiBookTracker.Repo.Migrations.ProviderSettings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:provider_settings, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :credential, :text
      add :enabled, :boolean, null: false
      add :provider, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:provider_settings, [:provider],
             name: "provider_settings_unique_provider_index"
           )

  end

  def down do
    drop_if_exists unique_index(:provider_settings, [:provider],
                     name: "provider_settings_unique_provider_index"
                   )

    drop table(:provider_settings)
  end
end
