defmodule CiBookTracker.Repo.Migrations.MakeWordGoalOptional do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  @disable_ddl_transaction true

  def up do
    execute "PRAGMA foreign_keys = OFF"
    execute "PRAGMA legacy_alter_table = ON"
    execute "ALTER TABLE reading_logs RENAME TO reading_logs_old"

    execute """
    CREATE TABLE reading_logs (
      updated_at TEXT NOT NULL,
      inserted_at TEXT NOT NULL,
      word_goal INTEGER,
      language_code TEXT NOT NULL,
      name TEXT NOT NULL,
      id TEXT NOT NULL PRIMARY KEY
    )
    """

    execute """
    INSERT INTO reading_logs
      (updated_at, inserted_at, word_goal, language_code, name, id)
    SELECT updated_at, inserted_at, word_goal, language_code, name, id
    FROM reading_logs_old
    """

    execute "DROP TABLE reading_logs_old"
    execute "PRAGMA legacy_alter_table = OFF"
    execute "PRAGMA foreign_keys = ON"
  end

  def down do
    execute "PRAGMA foreign_keys = OFF"
    execute "PRAGMA legacy_alter_table = ON"
    execute "ALTER TABLE reading_logs RENAME TO reading_logs_old"

    execute """
    CREATE TABLE reading_logs (
      updated_at TEXT NOT NULL,
      inserted_at TEXT NOT NULL,
      word_goal INTEGER NOT NULL,
      language_code TEXT NOT NULL,
      name TEXT NOT NULL,
      id TEXT NOT NULL PRIMARY KEY
    )
    """

    execute """
    INSERT INTO reading_logs
      (updated_at, inserted_at, word_goal, language_code, name, id)
    SELECT updated_at, inserted_at, word_goal, language_code, name, id
    FROM reading_logs_old
    """

    execute "DROP TABLE reading_logs_old"
    execute "PRAGMA legacy_alter_table = OFF"
    execute "PRAGMA foreign_keys = ON"
  end
end
